version: "3.7"
services:
   martianrobots:
    container_name: martianrobots
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Container
    ports:
      - 5000:80
    depends_on:
      - mongo
      
   mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
      
   frontend:
    container_name: martianui
    build:
        context: /ui
        dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mongo
      - martianrobots     
    